name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build the app
      run: |
        go build -o main go-app.go

    - name: Run tests
      run: |
        go test ./...

  deploy-appengine:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.4.0
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Use the key directly for security
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to App Engine
      uses: GoogleCloudPlatform/github-actions/deploy-appengine@v0.7.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service: "default"
        region: "us-central1"
        deployables: |
          - go-app.yaml
