name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      run: |
        sudo apt-get update
        sudo apt-get install golang-go -y
    - name: Build the app
      run: go build -o main .
    - name: Run tests
      run: go test ./...

  # Deploy to App Engine
  deploy-appengine:
    runs-on: ubuntu-latest
    needs: build-and-test  # Trigger this job after build-and-test finishes
    steps:
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        project: ${{ secrets.GCP_PROJECT_ID }}
        service: "go-app"  # Replace with your desired service name
        region: "ap-southeast-1" # Asia Pacific (Singapore) // Choose your deployment region
        version: "1.0.0"  # Specify version (update for each deployment)
        source: "**/*"  # Deploys all files in the repository

