name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Updated Install Go step
      - name: Install Go
        run: |
          wget https://dl.google.com/go/go1.20.0.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.20.0.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

      - name: Build the app
        run: go build -o main .

      - name: Run tests
        run: go test ./...

  # Deploy to App Engine
  deploy-appengine:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: google-github-actions/auth@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project: ${{ secrets.GCP_PROJECT_ID }}
          service: "go-app"
          region: "asia-southeast1-a"
          version: "1.0.0"
          source: "**/*"
