name: Secure CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build the app
        run: |
          go build -o main go-app.go

      - name: Run tests
        run: |
          go test ./...

  deploy-appengine:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Set project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Access service account key securely
        run: |
          gcloud secrets versions access latest --secret="${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}" --project="${{ secrets.GCP_PROJECT_ID }}" > key.json
          chmod 600 key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authenticate with Google Cloud SDK
        run: |
          gcloud auth activate-service-account --key-file=key.json

      # Add remaining steps for deployment, if any
